### PR TITLE
Change 'import dpath' to 'import dpath.util'

### PR DESCRIPTION
**Pull request by hundahl**
Importing has changed with dpath-2.0.1

### CODE REVIEW

**Comment by mraspaud** [comment]
https://github.com/akesterson/dpath-python/issues/119

**Comment by mraspaud** [comment]
This seems to be a bug in dpath >= 2.0, so I'm going to wait for an answer from the dpath devs before taking action on this one.

**Comment by mraspaud** [comment]
For now, just install trollflow2 with dpath < 2.0 works

**Comment by pnuu** [comment]
I've forced the dpath version to < 1.5 in #73 which is now merged. I'll close this, and we can do further updates when the dpath issue @mraspaud reported and linked has been handled.

**Pull request closed without merging**
