### PR TITLE
Profile CLI run through dask

### PR DESCRIPTION
**Pull request by gerritholl**
For the CLI added in #184, add an option to profile the results using dask.diagnostics and visualize the results as a bokeh plot.

 - [x] Tests added  
 - [x] Tests passed 
 - [x] Passes ``flake8 trollflow2`` 
 - [x] Fully documented

### CODE REVIEW

**Comment by gerritholl** [comment]
We should merge #184 first.

**Comment by djhoese** [comment]
In polar2grid I think I called this --create-profile and nargs=?. That way I could provide a default HTML file name with info about the reader and writer being used and the current time.

**Comment by gerritholl** [comment]
> In polar2grid I think I called this --create-profile and nargs=?. That way I could provide a default HTML file name with info about the reader and writer being used and the current time.

I don't understand what you mean by "provide a default HTML file name".  With `nargs=?` you'd be giving multiple HTML file names to write to?  Info about the reader and writer, you mean by string substitution?

**Comment by djhoese** [comment]
Sorry. With `nargs="?"` and `default=False` you can pass only `--create-profile` to the CLI and `args.create_profile` will be `None` (if I remember correctly). Or you can do `--create-profile profile_my_filename.html`. Or if it isn't specified at all then `args.create_profile` is `False`. If it is `None` I then later set it to `"{project_name}_{glue_name}_{start_time:%Y%m%d_%H%M%S}.html"` where for P2G `project_name` is either "geo2grid" or "polar2grid", `glue_name` is `<reader_name>2<writer_name>` and start_time is the current time when the script is executed. I also allow the user to specify `end_time` in the format string.

I turned it into a context manager:

https://github.com/ssec/polar2grid/blob/4c470fa9de54c4b141cf4a5301a90005f35d5c84/polar2grid/glue.py#L241-L266

You'll notice I also print out a `file://` version of the HTML path so in my Terminal on linux it is Ctrl + left click-able and opens in my browser.

**Comment by pnuu** [comment]
I merged `main` to the PR and tried to resolve the conflicts. Lets see what the CI says.

**Review by pnuu — APPROVED** [review]
LGTM

**Review by mraspaud — APPROVED** [review]
LGTM

**Pull request merged**
