### PR TITLE
Reduce test warnings

### PR DESCRIPTION
**Pull request by pnuu**
This PR aims at reducing warnings emitted when running the tests.

:heavy_check_mark: Needs rebasing after #201 has been merged.

 - [ ] Closes #xxxx 
 - [ ] Tests added  
 - [x] Tests passed 
 - [x] Passes ``flake8 trollflow2`` 
 - [ ] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Comment by pnuu** [comment]
I'm not actually sure we can start using timezone-aware datetimes before Satpy and everything else is doing that.

**Comment by pnuu** [comment]
For Python 3.12 the number of warnings dropped from 897 to 17 (locally, 16 on CI where there's a newer `dateutils`). For 3.11 the figures are 880 -> 4 (5 in CI, can't spot where the difference is).

The `AttributeError: 'NoneType' object has no attribute 'setsockopt'` needs to be fixed in the `patched_publisher` of Posttroll.

**Comment by pnuu** [comment]
The leftover warnings:

```
trollflow2/tests/test_trollflow2.py::TestFilePublisher::test_filepublisher_with_compose
trollflow2/tests/test_trollflow2.py::TestFilePublisher::test_filepublisher_without_compose
  /home/lahtinep/mambaforge/envs/py311/lib/python3.11/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function FilePublisher.__del__ at 0x7ceffb6184a0>
  
  Traceback (most recent call last):
    File "/home/lahtinep/Software/pytroll/pytroll_packages/trollflow2/trollflow2/plugins/__init__.py", line 560, in __del__
      self.stop()
    File "/home/lahtinep/Software/pytroll/pytroll_packages/trollflow2/trollflow2/plugins/__init__.py", line 555, in stop
      self.pub.stop()
    File "/home/lahtinep/Software/pytroll/pytroll_packages/posttroll/posttroll/publisher.py", line 144, in stop
      self.publish_socket.setsockopt(zmq.LINGER, 1)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: 'NoneType' object has no attribute 'setsockopt'
 ```
Easy to get rid off by adding `if self.publish.socket:` in `posttroll.publisher.Publisher.stop`, which I tested locally and works for this. I'm not sure why the patching in `posttroll.testing.patched_publisher` doesn't already handle this.

```
trollflow2/tests/test_trollflow2.py::TestCheckSunlightCoverage::test_fully_sunlit_scene_returns_full_coverage
  /home/lahtinep/mambaforge/envs/py311/lib/python3.11/site-packages/pyproj/crs/crs.py:1293: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
    proj = self._crs.to_proj4(version=version)
```
This should be suppressed in `from trollsched.satpass import Pass`.

**Review by mraspaud — APPROVED** [review]
Thanks for fixing these, lgtm.

**Pull request merged**
